version: '3'

services:
  neo4j:
    image: neo4j:latest
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/secret
      NEO4J_dbms_logs_debug_level: DEBUG

  parsley:
    image: tangibleconcepts/parsley:0.1.0
    hostname: parsley
    container_name: parsley
    environment:
      - neo4j.url=bolt://neo4j:7687
      - neo4j.user=neo4j
      - neo4j.password=secret
    links:
      - neo4j
    depends_on:
      - neo4j
    volumes:
    - ./maps:/maps

